### ISSUE TITLE
API view-order-status: to update response

### ISSUE THREAD

**Issue by payen83** [payen83/HSWeb#10]
This api response should be similar to API pending-jobs, but this one for customer view **(Done)**

<img width="644" alt="screen shot 2018-07-03 at 4 04 25 pm" src="https://user-images.githubusercontent.com/13946724/42216816-ab8a9d14-7ef5-11e8-9c8a-51f71c2c2f78.png">

**Comment by payen83** [comment]
Additional field needed for orders field: product ImageURL (similar to active jobs)

**Comment by arifahmunirahzul** [comment]
Done 

![image](https://user-images.githubusercontent.com/38314829/42745553-fff59678-8905-11e8-89a1-3e361c59c2ad.png)

**Comment by payen83** [comment]
Checked and done
