### ISSUE TITLE
Job list page: To view job details and status

### ISSUE THREAD

**Issue by payen83** [payen83/HSWeb#13]
right now only show the list of order status. **(Done)**

**Comment by arifahmunirahzul** [comment]
Done

![image](https://user-images.githubusercontent.com/38314829/42494381-b576ceee-8452-11e8-918d-8bf48efc24e3.png)

![image](https://user-images.githubusercontent.com/38314829/42494415-cfb6ad42-8452-11e8-9ceb-ce5c4701d6db.png)

![image](https://user-images.githubusercontent.com/38314829/42494439-e23beacc-8452-11e8-9326-a086f04c8893.png)

**Comment by payen83** [comment]
Job details should include special note as well

**Comment by arifahmunirahzul** [comment]
**Done** 

![image](https://user-images.githubusercontent.com/38314829/43055459-3e142ede-8e69-11e8-9dd6-e827012af276.png)

**Comment by payen83** [comment]
Please remove lat and lng & put special not at another container next to delivery address

**Comment by arifahmunirahzul** [comment]
**Done**

![image](https://user-images.githubusercontent.com/38314829/43240815-edd66a2c-90ca-11e8-8226-c75a220d48df.png)

**Comment by payen83** [comment]
Verified. Thanks
