### ISSUE TITLE
Agent product inventory

### ISSUE THREAD

**Issue by payen83** [payen83/HSWeb#14]
At the main page just show agents name and total number of products, when user click the name the details of product list will show by the specific agent. Group the products based on agent name. **(Done)**

**Comment by arifahmunirahzul** [comment]
Done
![image](https://user-images.githubusercontent.com/38314829/42494298-74affe94-8452-11e8-8b45-32e2b603c55e.png)

![image](https://user-images.githubusercontent.com/38314829/42494331-8e6c4ef0-8452-11e8-819f-3a3700b433bb.png)

![image](https://user-images.githubusercontent.com/38314829/42494350-9eb5813c-8452-11e8-9e30-5edd2bd72ab7.png)

**Comment by payen83** [comment]
checked and validated
