### ISSUE TITLE
API: need pending, active, pending-completion and completed jobs for specific customer

### ISSUE THREAD

**Issue by payen83** [payen83/HSWeb#16]
**(Done)**

url: healthshoppe.elyzian.xyz/api/job/view-order-status/{user_id}

**Comment by arifahmunirahzul** [comment]
**(Done)**

url: healthshoppe.elyzian.xyz/api/job/view-order-status/{user_id}

![image](https://user-images.githubusercontent.com/38314829/42494217-2d1d2034-8452-11e8-8f6d-2daf1216960d.png)

**Comment by payen83** [comment]
verified, thanks
