### ISSUE TITLE
API: need job status history based on job id

### ISSUE THREAD

**Issue by payen83** [payen83/HSWeb#17]
**(Done)**

url: healthshoppe.elyzian.xyz/api/job/view-order-timeline/{JobID}

**Comment by arifahmunirahzul** [comment]
**(Done)**

url: healthshoppe.elyzian.xyz/api/job/view-order-timeline/{JobID}

![image](https://user-images.githubusercontent.com/38314829/42494151-fa20080e-8451-11e8-8c44-21ceb965bbc7.png)

**Comment by payen83** [comment]
great, thanks
