### ISSUE TITLE
API: view-order-status should include agent details

### ISSUE THREAD

**Issue by payen83** [payen83/HSWeb#18]
Please include agent details as below for API: `http://healthshoppe.elyzian.xyz/api/job/view-order-status/{id}`**(DONE)**

- Agent name
- Agent image url
- Agent phone number

**Comment by arifahmunirahzul** [comment]
Done add agent id

![image](https://user-images.githubusercontent.com/38314829/42494077-c1c1ad0a-8451-11e8-809d-166dbfff0e18.png)

**Comment by payen83** [comment]
ok done
