### ISSUE TITLE
Login page: should have notification on invalid username/password

### ISSUE THREAD

**Issue by payen83** [payen83/HSWeb#2]
Error text should appear if user enter wrong username or password.

**Comment by arifahmunirahzul** [comment]
Done

![image](https://user-images.githubusercontent.com/38314829/42742175-7537e6c2-88eb-11e8-9fae-39bc633132f9.png)

**Comment by arifahmunirahzul** [comment]
**Done**

Only **(Super Admin & Admin )** can access trough healthshoppe website

**Comment by payen83** [comment]
Check and verified
