### ISSUE TITLE
Withdraw Web & API: Error When Trying to Approve Request

### ISSUE THREAD

**Issue by payen83** [payen83/HSWeb#20]
1. Error when try to approve withdraw request (ada masukkan pdf dengan date transaction)
<img width="1149" alt="screen shot 2018-07-12 at 6 46 22 pm" src="https://user-images.githubusercontent.com/13946724/42629029-90f66ef4-8604-11e8-9b82-c5008fa4414f.png">

2. When try to do request withdraw from mobile app (API) for 2nd time, the request still successful event user already made a request earlier. This make the request list shows more than 1 time. System should check if the agent still have the balance for the request (the requested amount should not exceed the wallet balance).

<img width="1124" alt="screen shot 2018-07-12 at 6 49 08 pm" src="https://user-images.githubusercontent.com/13946724/42629095-d5d4c660-8604-11e8-8eb6-b5b607937937.png">

3. When user make request, the wallet amount **should be deducted and put into pending amount**.. then after admin approves the request then pending amount will be set to zero.

**Example**:

1. Before agent request withdraw:
```
{
    "wallets": [
        {
            "name": "Izham Zaile",
            "email": "iz.zaile@gmail.com",
            "u_bankname": "CIMB BHD",
            "u_accnumber": "7768093458",
            "amount": "3400",
            "pending_approval": "0"
        }
    ]
}
```

2. After agent request withdraw:
```
{
    "wallets": [
        {
            "name": "Izham Zaile",
            "email": "iz.zaile@gmail.com",
            "u_bankname": "CIMB BHD",
            "u_accnumber": "7768093458",
            "amount": "0",
            "pending_approval": "3400"
        }
    ]
}
```

3. After admin approve withdraw request:
```
{
    "wallets": [
        {
            "name": "Izham Zaile",
            "email": "iz.zaile@gmail.com",
            "u_bankname": "CIMB BHD",
            "u_accnumber": "7768093458",
            "amount": "0",
            "pending_approval": "0"
        }
    ]
}
```

**Comment by arifahmunirahzul** [comment]
Done 

1. Before make withdraw request
![image](https://user-images.githubusercontent.com/38314829/42677047-06c26cb6-86ad-11e8-8512-4d6d598bf2ed.png)

2. Done make withdraw request

![image](https://user-images.githubusercontent.com/38314829/42677150-7c3ce412-86ad-11e8-9735-61914cfcf528.png)

3. Only appear active withrawal

![image](https://user-images.githubusercontent.com/38314829/42677186-99374f80-86ad-11e8-8c4f-0b6c535ea607.png)

4. Insert data after approval withdraw

![image](https://user-images.githubusercontent.com/38314829/42677444-5d0079c8-86ae-11e8-9965-4041fca063a2.png)

5. Done withdraw

![image](https://user-images.githubusercontent.com/38314829/42677466-6e0ba242-86ae-11e8-9927-4a744466110a.png)

**Comment by payen83** [comment]
For number 2 : Done make withdraw request, amount should deduct from current wallet amount after withdraw request. For example, if user's wallet balance is $5500, then withdraw request is $5000, after request, the balance amount should appear as $500 (because 5500 - 5000 = 500). 
 
Should appear like this:
```
{
    "wallets": 
        {
            "name": "Izham Zaile",
            "email": "iz.zaile@gmail.com",
            "u_bankname": "CIMB BHD",
            "u_accnumber": "7768093458",
            "amount": "500",
            "pending_approval": "5000"
        }
}
```

**Comment by arifahmunirahzul** [comment]
**Done**

1. Check balance

![image](https://user-images.githubusercontent.com/38314829/42730770-c0e8db4c-882f-11e8-84cc-f2196de3b095.png)

2. Withdraw Request

![image](https://user-images.githubusercontent.com/38314829/42730773-d95c6950-882f-11e8-884d-9aa1fe6cc41a.png)

3.Balance after withraw request

![image](https://user-images.githubusercontent.com/38314829/42730777-f9b65d64-882f-11e8-950e-097b66824ad5.png)

4. Balance after request has been approved

![image](https://user-images.githubusercontent.com/38314829/42730793-619b7504-8830-11e8-84b7-7f07f673b46d.png)

**Comment by payen83** [comment]
check and validated
