### ISSUE TITLE
API: Withdraw request - amount should allow $5,000 and less

### ISSUE THREAD

**Issue by payen83** [payen83/HSWeb#21]
Not autorized if request amount is $5,000.. if $5,001 and above baru not allowed.

<img width="508" alt="screen shot 2018-07-14 at 11 02 32 am" src="https://user-images.githubusercontent.com/13946724/42720211-9198ad20-8755-11e8-8ac3-b49c3c41c5cd.png">

**Comment by arifahmunirahzul** [comment]
Done

![image](https://user-images.githubusercontent.com/38314829/42730252-af65808a-8822-11e8-87ca-a962584f6f3f.png)

![image](https://user-images.githubusercontent.com/38314829/42730254-c25e8dbc-8822-11e8-8e3b-c1d0fcf1b666.png)

**Comment by payen83** [comment]
noted
